In [1]:
import numpy as np

In [2]:
nparray = np.arange(10000) # create numpy array
mylist = list(range(10000)) # create ordinary list

In [3]:
%time for _ in range(10): nparray2 = nparray ** 2
# calculate time execution on numpy array

CPU times: user 3.35 ms, sys: 1.02 ms, total: 4.37 ms
Wall time: 2.92 ms


In [4]:
%time for _ in range(10): mylist2 = [x ** 2 for x in mylist]
# calculate time execution on ordinary list

CPU times: user 11.4 ms, sys: 28 μs, total: 11.5 ms
Wall time: 10.8 ms


We saw above that operation on numpy array is more efficient than on list.

## N-dimensional array object ndarray

### 1darray

In [5]:
lis = [123, 456, 789]
array_1d = np.array(lis)

In [6]:
array_1d

array([123, 456, 789])

In [7]:
# get dimension of array with:
print(array_1d.ndim)
print(array_1d.shape)

1
(3,)


### 2darray

In [8]:
lis2 = [[12, 34, 56], [78, 910, 1112], [1415, 1617, 1819]]
array_2d = np.array(lis2)

In [9]:
print(array_2d.ndim)
print(array_2d.shape)

2
(3, 3)


In [10]:
print(array_2d.ndim)
print(array_2d.shape)

2
(3, 3)


In [11]:
array_2d

array([[  12,   34,   56],
       [  78,  910, 1112],
       [1415, 1617, 1819]])

### 3darray

In [12]:
li1 = [[1, 2, 3], [4, 5, 6]]
li2 = [[7, 8, 9], [10, 11, 12]]
li3 = [[13, 14, 15], [16, 17, 18]]
lis3 = [li1, li2, li3]
array_3d = np.array(lis3)

In [13]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [14]:
print(array_3d.ndim)
print(array_3d.shape)

3
(3, 2, 3)


In [15]:
# randn function takes a tuples to specify a size of array.
print(np.random.randn(3))
print(np.random.randn(2, 2))
print(np.random.randn(3, 4, 5))

[-0.691854   -0.25352261  0.09419136]
[[-1.13892819  0.1114885 ]
 [-2.44784211  0.19109873]]
[[[-1.20434317  0.13112956 -1.5927547   0.25823318  0.84563496]
  [-0.90193279 -1.01619635  0.75100772  0.77183839 -0.37181556]
  [-0.54859686 -0.7602337   0.17088795 -0.88942547  1.93393211]
  [-0.5420959  -0.536128    0.40213594 -0.69092869  1.49806976]]

 [[ 0.72805458 -0.64931946  0.64518625 -0.16063117  1.77012881]
  [-1.39368098 -0.64787992  0.87987033  0.73820187  1.40379588]
  [ 0.52244327  0.83694836  1.45100851 -0.20095051 -0.07006562]
  [ 0.98050392  0.8571719  -1.07409899  0.60945641  0.09236782]]

 [[-0.02592545  1.75601488  0.26069349 -0.47515923  0.25068693]
  [-1.65718304 -2.92215167  0.8378662  -0.07092113 -0.1599682 ]
  [ 0.27051539 -1.54722466 -0.32944897 -0.39166268 -0.68945539]
  [-1.39869339 -0.45820607 -0.06698814  0.91813399 -0.38216903]]]


In [16]:
np.zeros(5) # create array of zeros

array([0., 0., 0., 0., 0.])

In [17]:
np.ones((5, 4)) # create array of ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.empty((2, 3, 4)) #  create array of garbage value

array([[[2.03619934e-315, 0.00000000e+000, 9.82157975e+252,
         8.89489936e+252],
        [6.01346954e-154, 6.01347002e-154, 6.01347002e-154,
         6.01347002e-154],
        [9.08366793e+223, 1.14177168e+243, 2.45126797e+198,
         1.06083187e-153]],

       [[2.35625393e+251, 6.01334511e-154, 6.01347002e-154,
         6.01347002e-154],
        [6.01347002e-154, 1.88556770e+122, 4.96820036e+180,
         6.80600993e+212],
        [1.10317376e+217, 1.19490107e+190, 2.06642651e+161,
         5.44760669e-109]]])

In [19]:
np.full((2, 3), 3) # crete an array fulled with a given value

array([[3, 3, 3],
       [3, 3, 3]])

In [20]:
np.linspace(5, 15, 5, retstep=True)

(array([ 5. ,  7.5, 10. , 12.5, 15. ]), np.float64(2.5))

In [21]:
np.linspace(5, 15, 5, dtype=int)

array([ 5,  7, 10, 12, 15])

In [22]:
array3d = np.arange(100)

In [23]:
array3d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [24]:
array3d.reshape(4, 5, 5)
#np.reshape(array3d, shape=(4, 5, 5), order='C')

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [25]:
array_1d.transpose() # to get transpose of a array

array([123, 456, 789])

In [26]:
array_2d.T # with propretie T

array([[  12,   78, 1415],
       [  34,  910, 1617],
       [  56, 1112, 1819]])

In [27]:
array_3d.transpose()

array([[[ 1,  7, 13],
        [ 4, 10, 16]],

       [[ 2,  8, 14],
        [ 5, 11, 17]],

       [[ 3,  9, 15],
        [ 6, 12, 18]]])

In [28]:
np.flip(array_2d) # this is to get a reversed of a given array

array([[1819, 1617, 1415],
       [1112,  910,   78],
       [  56,   34,   12]])

In [29]:
np.flip(array_2d, axis=0) # by reverse only the rows

array([[1415, 1617, 1819],
       [  78,  910, 1112],
       [  12,   34,   56]])

In [30]:
np.flip(array_2d, axis=1) # by reverse only the colomns

array([[  56,   34,   12],
       [1112,  910,   78],
       [1819, 1617, 1415]])

In [31]:
# we have ndarray.flatten() and ndarray.ravel()
# for making a copy of array, but with ravel any change on new array will affect the parent array
# what is not the same flatten.

In [32]:
a = np.reshape(np.arange(10), shape=(2, 5), order='C')
b = a.flatten()
c = a.ravel()

In [33]:
b[4] = 100
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [34]:
c[4] = 100
print(a)

[[  0   1   2   3 100]
 [  5   6   7   8   9]]


## Matrix
Matrices can be conceptualized as a set of column vectors stacked next to each other,
as a set of row vectors layered on top of each other.

### Diagonal
It is refere to all element in matrix where row index is equal to column index (i == j)

In [35]:
# np.diag result depend on input

# 1
res1 = np.diag(np.array([ [1,2,3],[4,5,6],[7,8,9] ])) 
print(res1) # return the diagonal of this matrix

# 2
res2 = np.diag(np.array([1,2,3]))
print(res2) # return a matrix with vector elements as diagonal element 

[1 5 9]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Triangular
Is matrix which all element are zero neither above or below main diagonal.
We have upper triangular (np.triu()) or lower triangular (np.tril()). 

In [36]:
np.triu(np.array([ [1,2,3,4],[6,7,8,9],[10,11,12,13], [14,15,16,17] ]), k=0)
# k=0 refere to main diagonal The identity matrix is a square diagonal matrix with all
# diagonal elements having a value of 1

array([[ 1,  2,  3,  4],
       [ 0,  7,  8,  9],
       [ 0,  0, 12, 13],
       [ 0,  0,  0, 17]])

In [37]:
np.triu(np.array([ [1,2,3,4],[6,7,8,9],[10,11,12,13], [14,15,16,17] ]), k=1)

array([[ 0,  2,  3,  4],
       [ 0,  0,  8,  9],
       [ 0,  0,  0, 13],
       [ 0,  0,  0,  0]])

In [38]:
np.triu(np.array([ [1,2,3,4],[6,7,8,9],[10,11,12,13], [14,15,16,17] ]), k=-1)

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [ 0, 11, 12, 13],
       [ 0,  0, 16, 17]])

In [39]:
np.tril(np.array([ [1,2,3,4],[6,7,8,9],[10,11,12,13], [14,15,16,17] ]), k=0)

array([[ 1,  0,  0,  0],
       [ 6,  7,  0,  0],
       [10, 11, 12,  0],
       [14, 15, 16, 17]])

In [40]:
np.tril(np.array([ [1,2,3,4],[6,7,8,9],[10,11,12,13], [14,15,16,17] ]), k=-1)

array([[ 0,  0,  0,  0],
       [ 6,  0,  0,  0],
       [10, 11,  0,  0],
       [14, 15, 16,  0]])

### Identity 
The identity matrix is matrix with all diagonal elements having a value of 1.

In [41]:
np.identity(4) # np.identity(k) ==> kxk

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
np.eye(4, 4, -1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## Operations on Matrix

In [44]:
mat1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
mat2 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
mat3 = np.array([ [1,2],[3,4],[5,6] ])

### Addition
matrix addition is defined only between two matrices of the same size.

In [45]:
mat1 + mat2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [46]:
# A + λI
mat1 + (-6)*np.eye(3, dtype=int)

array([[-5,  2,  3],
       [ 4, -1,  6],
       [ 7,  8,  3]])

### Multiplication

In [47]:
np.multiply(mat1, mat2) # hadamard multiplication

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

### Transpose

In [48]:
np.transpose(mat1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Dot, Inner and Outer product 

In [49]:
np.dot(mat1, mat1) # process matrix mutiplication

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
mat1@mat2

In [50]:
np.inner(mat1, mat2) # mutiply row in mat1 by row in mat2

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [51]:
np.outer(mat1, mat2) # return matrix with len(mat1)xlen(mat2)
# each element in mat1 will multiply all element of mat2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])