In [1]:
import numpy as np
np.set_printoptions(precision=2)

### What version of numpy are you using?

In [2]:
print(np.__version__)

2.5.2


### Dispaly array with 10 elements in reverse order

In [3]:
A = np.arange(10)

In [4]:
A[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### Triple the value of each elementin the array vreated previously

In [5]:
A * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

### Create array with 20 zeros; erery fifth element equals four

In [6]:
A_zeros = np.zeros(20)
A_zeros[0::5] = 4
A_zeros

array([4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0., 0., 0., 0., 4., 0.,
       0., 0., 0.])

### Create 5x5 matrix with integer compenents

In [7]:
eye_5_5 = np.asmatrix(np.eye(5, dtype=int))
eye_5_5

matrix([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1]])

### Find the meam of a vector with 30 random elements. Can you guess the approximate value for the mean?

In [8]:
A_30 = np.random.randn(30)
A_30.mean()

np.float64(0.3162703307545557)

#### repeat

In [9]:
A_30 = np.random.randn(30)
A_30.mean()

np.float64(0.34920119300060826)

### Create an 8x8 checker with zeros and ones 

In [10]:
A_8_8 = np.zeros(shape=(8, 8), dtype=int)
A_8_8[0::2, 0::2] = 1

# A_8_8 = A_8_8.reshape((8, 8))
A_8_8

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

### Create a sorted  vector that containt 'n' random numbers

In [11]:
A_sorted = np.random.rand(10)
np.sort(A_sorted)

array([0.07, 0.08, 0.17, 0.3 , 0.37, 0.44, 0.52, 0.61, 0.62, 0.8 ])

### Without sorting vector, replace largest element in random array by 1234

In [12]:
A_sorted[A_sorted.argmax()] = 1234
print(A_sorted)

[5.24e-01 7.52e-02 3.67e-01 6.14e-01 1.65e-01 6.23e-01 4.39e-01 6.78e-02
 1.23e+03 2.98e-01]


### Given the following data type and data set; sort according to 'height'

In [13]:
camelot_dtype = [('name', 'S10'), ('height', float), ('age', int)]
camelot_value = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.6, 39)]

In [14]:
A_dtype = np.asarray(camelot_value, dtype=camelot_dtype)
A_dtype

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.6, 39)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [15]:
for value in np.sort(A_dtype, order='height'):
    print(value)

(b'Galahad', 1.6, 39)
(b'Arthur', 1.8, 41)
(b'Lancelot', 1.9, 38)


### Make an array read-only (immuatable)

In [16]:
Array_ = np.array(np.arange(12))
Array_.flags.writeable = False
Array_[4] = 123445

ValueError: assignment destination is read-only

### print enumarated value in 3x3 array

In [18]:
array_3_3 = np.arange(9).reshape(3, 3)

for index, value in enumerate(array_3_3):
    print(index, value)

0 [0 1 2]
1 [3 4 5]
2 [6 7 8]
